### ISSUE TITLE
有没有恰当的方法控制module的加载顺序

### ISSUE THREAD

**Issue by SaulLawliet** [funny/go-project-demo#3]
Hi, 你好, 以下是我的问题 :)  
默认的加载顺序是字典序的倒叙, 比如下面这个的加载顺序是先player.init()后item.init().
``` go
import (
	_ "github.com/funny/go-project-demo/server1/module/item"
	_ "github.com/funny/go-project-demo/server1/module/player"
)
```
现在假设, 我在player.init()中, 调用了item里的对象(此时item还没有init), 程序出错...
**问题1. 出现这种情况是我设计的问题么?**

如果不是的话. 我的解决方法是把item的包名修改成了z_item(这样就会先于player执行init). 
但是这种解决方式肯定不够优雅.
**问题2. 有没有其他的方式控制包的加载顺序**

望解答, thx ;)

**Comment by idada** [comment]
好问题。

我们项目里面没有遇到这样的情况，因为我们的模块是没有状态的，需要初始化的只有一些服务。

如果要做的话，只好每个Module都自己做个初始化函数不要用包的init函数了，然后在一个总的入口里面按所需的顺序逐个初始化下来。

但是这样的问题如果进一步推演，会不会出现初始化过程的循环依赖呢？比如A初始化前B需要初始化好，B初始化前需要C先初始化好，C初始化又依赖A先初始化，这样就死循环了。

所以初始化恐怕不能太零散的加，否则没办法控制。

**Comment by SaulLawliet** [comment]
如果死循环了, 就是设计的问题吧...
多谢解答~
